# Workflow for building and deploying a Hexo site with Butterfly theme to GitHub Pages
name: Deploy Hexo with Butterfly Theme to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # Fetch submodules if any

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      
      - name: Install Global Dependencies
        run: npm install -g hexo-cli
        
      - name: Install Dependencies
        run: |
          npm install hexo
          npm install hexo-generator-archive
          npm install hexo-generator-category
          npm install hexo-generator-index
          npm install hexo-generator-tag
          npm install hexo-renderer-ejs
          npm install hexo-renderer-marked
          npm install hexo-renderer-pug
          npm install hexo-renderer-stylus
          npm install hexo-server
          npm install hexo-theme-butterfly
          npm install hexo-wordcount
          npm install hexo-generator-search
          npm install hexo-generator-sitemap
          npm install hexo-generator-feed
          npm install hexo-generator-search
          npm install hexo-generator-searchdb
          npm install hexo-theme-landscape
        
      - name: Build Hexo Site
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
